---
title: "Absentee Voters"
format: 
  html:
    embed-resources: true
editor: visual
execute: 
  echo: false
  warning: false
  message: false
---

```{r setup}
library(tidyverse)
library(sf)
library(leaflet)
library(mapboxapi)
library(RColorBrewer)
library(colorspace)
library(glue)

d <- read_csv("data/ref_results.csv")
dd <- d |> 
  mutate(WARD = str_remove(ward, "City of Milwaukee Ward ") |> 
           str_trim(),
         margin_n = yes - no,
         margin_p = (yes-no) / (yes+no))

w <- st_read("data/wards/votingwards_April2023.shp", quiet = TRUE)

dw <- left_join(dd, w) |> 
  st_as_sf() |> 
  st_transform(crs = 4326)

# dw |> 
#   ggplot(aes(fill = n)) +
#   geom_sf(color = "white", linewidth = .1) +
#   scale_fill_viridis_c()
pa <- diverge_hcl(5, "Purple-Green")
pal <- colorBin(rev(pa), domain = c(-385, 385))

```

The map below shows absentee voting prior to election day for the Spring Election in Milwaukee. Boundaries represent wards.

```{r map}
#| fig-height: 11

leaflet(dw) |> 
  addMapboxTiles(style_id = "light-v11",
                 username = "mapbox", 
                 scaling_factor = "0.5x") |> 
  addPolygons(weight = 2, 
              fillColor = ~pal(margin_n), fillOpacity = .8,
              color = "white", 
              popup = glue("Ward: {dw$WARD}<br>Yes Margin: {dw$margin_n}"), 
              highlight = highlightOptions(color = "black", fillColor = "white",
                                           fillOpacity = .25, bringToFront = TRUE)) |> 
  addLegend(pal = pal, values = ~n, opacity = 0.9, title = "Yes Margin",
            position = "topright")
```
